version: '3.8'

services:
  app:
    image: mjlscna/ihomis-reports-app:latest
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9000:9000"  # if you want direct PHP-FPM access (optional)
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
